spring:
  profiles:
    active: local

---
spring:
  profiles: test

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 10080
